  /**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  cdmSideBar:  [
    'codrone-mini/cdm',
    {
      type: 'category',
      label: 'Connection',
      items: [
        {
          type: 'autogenerated',
          dirName: 'codrone-mini/01-Connection', // Generate sidebar slice from docs/tutorials/easy
        }
      ],
    },
    {
      type: 'category',
      label: 'Flight Commands (Start / Stop)',
      items: [
        {
          type: 'autogenerated',
          dirName: 'codrone-mini/02-Flight-Commands-Start-Stop', 
        }
      ],
    },
    {
      type: 'category',
      label: 'Flight Commands (Movement)',
      items: [
        {
          type: 'autogenerated',
          dirName: 'codrone-mini/03-Flight-Commands-Movement', 
        }
      ],
    },
    {
      type: 'category',
      label: 'Flight Variables',
      items: [
        {
          type: 'autogenerated',
          dirName: 'codrone-mini/04-Flight-Variables', 
        }
      ],
    },
    {
      type: 'category',
      label: 'LED',
      items: [
        {
          type: 'autogenerated',
          dirName: 'codrone-mini/05-LED', 
        }
      ],
    },
    {
      type: 'category',
      label: 'Status Checkers',
      items: [
        {
          type: 'autogenerated',
          dirName: 'codrone-mini/06-Status-Checkers', 
        }
      ],
    },
    {
      type: 'category',
      label: 'Sensors',
      items: [
        {
          type: 'autogenerated',
          dirName: 'codrone-mini/07-Sensors', 
        }
      ],
    },
  ],
  zumiSideBar:  [
    'zumi/home',
    {
      type: 'category',
      label: 'MPU',
      items: [
        {
          type: 'autogenerated',
          dirName: 'zumi/01-MPU', 
        }
      ],
    },
    {
      type: 'category',
      label: 'Sensors',
      items: [
        {
          type: 'autogenerated',
          dirName: 'zumi/02-Sensors', 
        }
      ],
    },
    {
      type: 'category',
      label: 'Driving',
      items: [
        {
          type: 'autogenerated',
          dirName: 'zumi/03-Driving', 
        }
      ],
    },
    {
      type: 'category',
      label: 'LEDs-and-Buzzer',
      items: [
        {
          type: 'autogenerated',
          dirName: 'zumi/04-LEDs-and-buzzer', 
        }
      ],
    },
    {
      type: 'category',
      label: 'Camera',
      items: [
        {
          type: 'autogenerated',
          dirName: 'zumi/05-Camera', 
        }
      ],
    },
    {
      type: 'category',
      label: 'Screen',
      items: [
        {
          type: 'autogenerated',
          dirName: 'zumi/06-Screen', 
        }
      ],
    },
    {
      type: 'category',
      label: 'Personality',
      items: [
        {
          type: 'autogenerated',
          dirName: 'zumi/07-Personality', 
        }
      ],
    },
  ],
  codroneProSideBar:  [
    'codrone-pro/home',
    'codrone-pro/arduino-changelog',
    'codrone-pro/python-changelog',
    {
      type: 'category',
      label: 'Connection',
      items: [
        {
          type: 'autogenerated',
          dirName: 'codrone-pro/03-connection', 
        }
      ],
    },
    {
      type: 'category',
      label: 'Flight Commands (Start/Stop)',
      items: [
        {
          type: 'autogenerated',
          dirName: 'codrone-pro/04-flight-commands-start-stop', 
        }
      ],
    },
    {
      type: 'category',
      label: 'Flight Commands (Movement)',
      items: [
        {
          type: 'autogenerated',
          dirName: 'codrone-pro/05-flight-commands-movement', 
        }
      ],
    },
    {
      type: 'category',
      label: 'Flight Variables',
      items: [
        {
          type: 'autogenerated',
          dirName: 'codrone-pro/06-flight-variables', 
        }
      ],
    },
    {
      type: 'category',
      label: 'LED',
      items: [
        {
          type: 'autogenerated',
          dirName: 'codrone-pro/07-led', 
        }
      ],
    },
    {
      type: 'category',
      label: 'Status Checkers',
      items: [
        {
          type: 'autogenerated',
          dirName: 'codrone-pro/08-status-checkers', 
        }
      ],
    },
    {
      type: 'category',
      label: 'Sensors',
      items: [
        {
          type: 'autogenerated',
          dirName: 'codrone-pro/09-sensors', 
        }
      ],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};
