module.exports = {
  someSidebar: [
    {
      type: 'category',
      label: 'Reference',
      items: [   'zumi/home/home', 'zumi/home/zumi-changelog', 'zumi/home/zumi-blockly-changelog', 'zumi/home/blockly-reference' , 'zumi/home/blockly-reference-senior',
      ],
    },
   
    {
      type: 'category',
      label: 'MPU',
      items: [
        {
          type: 'autogenerated',
          dirName: 'zumi/01-MPU', 
        }
      ],
    },{
      type: 'category',
      label: 'Sensors',
      items: [
        {
          type: 'autogenerated',
          dirName: 'zumi/02-Sensors', 
        }
      ],
    },
    {
      type: 'category',
      label: 'Driving',
      items: [
        {
          type: 'autogenerated',
          dirName: 'zumi/03-Driving', 
        }
      ],
    },
    {
      type: 'category',
      label: 'LEDs-and-Buzzer',
      items: [
        {
          type: 'autogenerated',
          dirName: 'zumi/04-LEDs-and-buzzer', 
        }
      ],
    },
    {
      type: 'category',
      label: 'Camera',
      items: [
        {
          type: 'autogenerated',
          dirName: 'zumi/05-Camera', 
        }
      ],
    },
    {
      type: 'category',
      label: 'Screen',
      items: [
        {
          type: 'autogenerated',
          dirName: 'zumi/06-Screen', 
        }
      ],
    },
    {
      type: 'category',
      label: 'Personality',
      items: [
        {
          type: 'autogenerated',
          dirName: 'zumi/07-Personality', 
        }
      ],
    },
  ],
  codroneProSideBar:  [
    {
      type: 'category',
      label: 'Reference',
      items: [  'codrone-pro/home/python-ref', 
      'codrone-pro/home/arduino-ref',
      'codrone-pro/home/codrone-pro-changelog', 
      'codrone-pro/blockly/reference_blockly', 
      'codrone-pro/blockly/reference_senior' 
      ],
    },
    {
      type: 'category',
      label: 'Connection',
      items: [
        {
          type: 'autogenerated',
          dirName: 'codrone-pro/03-connection', 
        }
      ],
    },
    {
      type: 'category',
      label: 'Flight Commands (Start/Stop)',
      items: [
        {
          type: 'autogenerated',
          dirName: 'codrone-pro/04-flight-commands-start-stop', 
        }
      ],
    },
    {
      type: 'category',
      label: 'Flight Commands (Movement)',
      items: [
        {
          type: 'autogenerated',
          dirName: 'codrone-pro/05-flight-commands-movement', 
        }
      ],
    },
    {
      type: 'category',
      label: 'Flight Variables',
      items: [
        {
          type: 'autogenerated',
          dirName: 'codrone-pro/06-flight-variables', 
        }
      ],
    },
    {
      type: 'category',
      label: 'LED',
      items: [
        {
          type: 'autogenerated',
          dirName: 'codrone-pro/07-led', 
        }
      ],
    },
    {
      type: 'category',
      label: 'Status Checkers',
      items: [
        {
          type: 'autogenerated',
          dirName: 'codrone-pro/08-status-checkers', 
        }
      ],
    },
    {
      type: 'category',
      label: 'Sensors',
      items: [
        {
          type: 'autogenerated',
          dirName: 'codrone-pro/09-sensors', 
        }
      ],
    },
  ],
  codroneEduSideBar:  [
    {
      type: 'category',
      label: 'Reference',
      items: [  'codrone-edu/python/home/python-reference', 'codrone-edu/blockly/reference', 'codrone-edu/blockly/reference-senior', 'codrone-edu/python/home/codrone-edu-changelog',
      ],
    },
    {
      type: 'category',
      label: 'Connection',
      items: [
        {
          type: 'autogenerated',
          dirName: 'codrone-edu/python/01-Connection', // Generate sidebar slice from docs/tutorials/easy
        }
      ],
    },
    {
      type: 'category',
      label: 'Flight Commands (Start / Stop)',
      items: [
        {
          type: 'autogenerated',
          dirName: 'codrone-edu/python/02-Flight-Commands-Start-Stop', 
        }
      ],
    },
    {
      type: 'category',
      label: 'Flight Commands (Movement)',
      items: [
        {
          type: 'autogenerated',
          dirName: 'codrone-edu/python/03-Flight-Commands-Movement', 
        }
      ],
    },
    {
      type: 'category',
      label: 'Flight Variables',
      items: [
        {
          type: 'autogenerated',
          dirName: 'codrone-edu/python/04-Flight-Variables', 
        }
      ],
    },
    {
      type: 'category',
      label: 'LED',
      items: [
        {
          type: 'autogenerated',
          dirName: 'codrone-edu/python/05-LED', 
        }
      ],
    },
    {
      type: 'category',
      label: 'Status Checkers',
      items: [
        {
          type: 'autogenerated',
          dirName: 'codrone-edu/python/06-Status-Checkers', 
        }
      ],
    },
    {
      type: 'category',
      label: 'Sensors',
      items: [
        {
          type: 'autogenerated',
          dirName: 'codrone-edu/python/07-Sensors', 
        }
      ],
    },
  ],
  cdmSideBar:  [
    {
      type: 'category',
      label: 'Reference',
      items: [  'codrone-mini/home/cdm', 'codrone-mini/home/cdm-mini-changelog',
      ],
    },
    {
      type: 'category',
      label: 'Connection',
      items: [
        {
          type: 'autogenerated',
          dirName: 'codrone-mini/01-Connection', // Generate sidebar slice from docs/tutorials/easy
        }
      ],
    },
    {
      type: 'category',
      label: 'Flight Commands (Start / Stop)',
      items: [
        {
          type: 'autogenerated',
          dirName: 'codrone-mini/02-Flight-Commands-Start-Stop', 
        }
      ],
    },
    {
      type: 'category',
      label: 'Flight Commands (Movement)',
      items: [
        {
          type: 'autogenerated',
          dirName: 'codrone-mini/03-Flight-Commands-Movement', 
        }
      ],
    },
    {
      type: 'category',
      label: 'Flight Variables',
      items: [
        {
          type: 'autogenerated',
          dirName: 'codrone-mini/04-Flight-Variables', 
        }
      ],
    },
    {
      type: 'category',
      label: 'LED',
      items: [
        {
          type: 'autogenerated',
          dirName: 'codrone-mini/05-LED', 
        }
      ],
    },
    {
      type: 'category',
      label: 'Status Checkers',
      items: [
        {
          type: 'autogenerated',
          dirName: 'codrone-mini/06-Status-Checkers', 
        }
      ],
    },
    {
      type: 'category',
      label: 'Sensors',
      items: [
        {
          type: 'autogenerated',
          dirName: 'codrone-mini/07-Sensors', 
        }
      ],
    },
  ],
  cdmBlocklySideBar:  [
    {
      type: 'category',
      label: 'Reference',
      items: [  'codrone-mini/blockly/reference_blockly',  'codrone-mini/blockly/reference_senior',
      ],
    },
  
    {
      type: 'category',
      label: 'Flight Commands',
      items: [
        {
          type: 'autogenerated',
          dirName: 'codrone-mini/blockly/01-Flight-Commands', 
        }
      ],
    },
    {
      type: 'category',
      label: 'Flight Commands Movements',
      items: [
        {
          type: 'autogenerated',
          dirName: 'codrone-mini/blockly/02-Flight-Commands-Movements', 
        }
      ],
    },
  ],
};
