module.exports = {
  someSidebar: [
    {
      type: 'category',
      label: 'Reference',
      items: [   'zumi/python/reference/library', 'zumi/python/changelog', 'zumi/blockly/changelog', 'zumi/blockly/reference/library-senior' , 'zumi/blockly/reference/library-junior',
      ],
    },
   
    {
      type: 'category',
      label: 'MPU',
      items: [
        {
          type: 'autogenerated',
          dirName: 'zumi/python/01-MPU', 
        }
      ],
    },{
      type: 'category',
      label: 'Sensors',
      items: [
        {
          type: 'autogenerated',
          dirName: 'zumi/python/02-Sensors', 
        }
      ],
    },
    {
      type: 'category',
      label: 'Driving',
      items: [
        {
          type: 'autogenerated',
          dirName: 'zumi/python/03-Driving', 
        }
      ],
    },
    {
      type: 'category',
      label: 'LEDs-and-Buzzer',
      items: [
        {
          type: 'autogenerated',
          dirName: 'zumi/python/04-LEDs-and-buzzer', 
        }
      ],
    },
    {
      type: 'category',
      label: 'Camera',
      items: [
        {
          type: 'autogenerated',
          dirName: 'zumi/python/05-Camera', 
        }
      ],
    },
    {
      type: 'category',
      label: 'Screen',
      items: [
        {
          type: 'autogenerated',
          dirName: 'zumi/python/06-Screen', 
        }
      ],
    },
    {
      type: 'category',
      label: 'Personality',
      items: [
        {
          type: 'autogenerated',
          dirName: 'zumi/python/07-Personality', 
        }
      ],
    },
  ],
  codroneProSideBar:  [
    {
      type: 'category',
      label: 'Reference',
      items: [  'codrone-pro/python/reference/library', 
      'codrone-pro/arduino/reference/library',
      'codrone-pro/blockly/reference_blockly', 
      'codrone-pro/blockly/reference_senior' 
      ],
    },
    {
      type: 'category',
      label: 'Connection',
      items: [
        {
          type: 'autogenerated',
          dirName: 'codrone-pro/python/03-connection', 
        }
      ],
    },
    {
      type: 'category',
      label: 'Flight Commands (Start/Stop)',
      items: [
        {
          type: 'autogenerated',
          dirName: 'codrone-pro/python/04-flight-commands-start-stop', 
        }
      ],
    },
    {
      type: 'category',
      label: 'Flight Commands (Movement)',
      items: [
        {
          type: 'autogenerated',
          dirName: 'codrone-pro/python/05-flight-commands-movement', 
        }
      ],
    },
    {
      type: 'category',
      label: 'Flight Variables',
      items: [
        {
          type: 'autogenerated',
          dirName: 'codrone-pro/python/06-flight-variables', 
        }
      ],
    },
    {
      type: 'category',
      label: 'LED',
      items: [
        {
          type: 'autogenerated',
          dirName: 'codrone-pro/python/07-led', 
        }
      ],
    },
    {
      type: 'category',
      label: 'Status Checkers',
      items: [
        {
          type: 'autogenerated',
          dirName: 'codrone-pro/python/08-status-checkers', 
        }
      ],
    },
    {
      type: 'category',
      label: 'Sensors',
      items: [
        {
          type: 'autogenerated',
          dirName: 'codrone-pro/python/09-sensors', 
        }
      ],
    },
  ],
  codroneEduSideBar:  [
    {
      type: 'category',
      label: 'Reference',
      items: [  'codrone-edu/python/reference/library', 'codrone-edu/python/changelog',
      ],
    },
    {
      type: 'category',
      label: 'Connection',
      items: [
        {
          type: 'autogenerated',
          dirName: 'codrone-edu/python/01-Connection', // Generate sidebar slice from docs/tutorials/easy
        }
      ],
    },
    {
      type: 'category',
      label: 'Flight Commands (Start / Stop)',
      items: [
        {
          type: 'autogenerated',
          dirName: 'codrone-edu/python/02-Flight-Commands-Start-Stop', 
        }
      ],
    },
    {
      type: 'category',
      label: 'Flight Commands (Movement)',
      items: [
        {
          type: 'autogenerated',
          dirName: 'codrone-edu/python/03-Flight-Commands-Movement', 
        }
      ],
    },
    {
      type: 'category',
      label: 'Flight Variables',
      items: [
        {
          type: 'autogenerated',
          dirName: 'codrone-edu/python/04-Flight-Variables', 
        }
      ],
    },
    {
      type: 'category',
      label: 'LED',
      items: [
        {
          type: 'autogenerated',
          dirName: 'codrone-edu/python/05-LED', 
        }
      ],
    },
    {
      type: 'category',
      label: 'Status Checkers',
      items: [
        {
          type: 'autogenerated',
          dirName: 'codrone-edu/python/06-Status-Checkers', 
        }
      ],
    },
    {
      type: 'category',
      label: 'Sensors',
      items: [
        {
          type: 'autogenerated',
          dirName: 'codrone-edu/python/07-Sensors', 
        }
      ],
    },
    
  ],
  codroneEduBlocklySideBar:  [
    {
      type: 'category',
      label: 'Reference',
      items: [  'codrone-edu/blockly/reference/library-senior'
      ],
    },
    {
      type: 'category',
      label: 'Flight Commands',
      items: [
        {
          type: 'autogenerated',
          dirName: 'codrone-edu/blockly/Senior/01-Flight-Commands', // Generate sidebar slice from docs/tutorials/easy
        }
      ],
    },
    {
      type: 'category',
      label: 'Flight Variables',
      items: [
        {
          type: 'autogenerated',
          dirName: 'codrone-edu/blockly/Senior/02-Flight-Variables', 
        }
      ],
    },
    {
      type: 'category',
      label: 'Status Checkers',
      items: [
        {
          type: 'autogenerated',
          dirName: 'codrone-edu/blockly/Senior/03-Status-Checkers', 
        }
      ],
    },
    {
      type: 'category',
      label: 'Lights',
      items: [
        {
          type: 'autogenerated',
          dirName: 'codrone-edu/blockly/Senior/04-Lights', 
        }
      ],
    },
    {
      type: 'category',
      label: 'Sensors',
      items: [
        {
          type: 'autogenerated',
          dirName: 'codrone-edu/blockly/Senior/05-Sensors', 
        }
      ],
    },
    {
      type: 'category',
      label: 'Sound',
      items: [
        {
          type: 'autogenerated',
          dirName: 'codrone-edu/blockly/Senior/06-Sound', 
        }
      ],
    },
    {
      type: 'category',
      label: 'Screen',
      items: [
        {
          type: 'autogenerated',
          dirName: 'codrone-edu/blockly/Senior/07-Screen', 
        }
      ],
    }
  ],
  cdmSideBar:  [
    {
      type: 'category',
      label: 'Reference',
      items: [  'codrone-mini/python/reference/library', 'codrone-mini/python/changelog',
      ],
    },
    {
      type: 'category',
      label: 'Connection',
      items: [
        {
          type: 'autogenerated',
          dirName: 'codrone-mini/python/01-Connection', // Generate sidebar slice from docs/tutorials/easy
        }
      ],
    },
    {
      type: 'category',
      label: 'Flight Commands (Start / Stop)',
      items: [
        {
          type: 'autogenerated',
          dirName: 'codrone-mini/python/02-Flight-Commands-Start-Stop', 
        }
      ],
    },
    {
      type: 'category',
      label: 'Flight Commands (Movement)',
      items: [
        {
          type: 'autogenerated',
          dirName: 'codrone-mini/python/03-Flight-Commands-Movement', 
        }
      ],
    },
    {
      type: 'category',
      label: 'Flight Variables',
      items: [
        {
          type: 'autogenerated',
          dirName: 'codrone-mini/python/04-Flight-Variables', 
        }
      ],
    },
    {
      type: 'category',
      label: 'LED',
      items: [
        {
          type: 'autogenerated',
          dirName: 'codrone-mini/python/05-LED', 
        }
      ],
    },
    {
      type: 'category',
      label: 'Status Checkers',
      items: [
        {
          type: 'autogenerated',
          dirName: 'codrone-mini/python/06-Status-Checkers', 
        }
      ],
    },
    {
      type: 'category',
      label: 'Sensors',
      items: [
        {
          type: 'autogenerated',
          dirName: 'codrone-mini/07-Sensors', 
        }
      ],
    },
  ],
  cdmBlocklySideBar:  [
    {
      type: 'category',
      label: 'Reference',
      items: [  'codrone-mini/blockly/reference_blockly',  'codrone-mini/blockly/reference_senior',
      ],
    },
  
    {
      type: 'category',
      label: 'Flight Commands',
      items: [
        {
          type: 'autogenerated',
          dirName: 'codrone-mini/blockly/01-Flight-Commands', 
        }
      ],
    },
    {
      type: 'category',
      label: 'Flight Commands Movements',
      items: [
        {
          type: 'autogenerated',
          dirName: 'codrone-mini/blockly/02-Flight-Commands-Movements', 
        }
      ],
    },
  ],
};
